### ISSUE TITLE
Spotify package causes crash in whole package system

### ISSUE THREAD

**Issue by moritzsternemann** [smpanaro/sublime-spotify#3]
After launching Sublime Text 3 (3065) on Mac OS 10.10.2 with Spotify 0.9.15.27.g87efe634 it loads all installed packages and then throws a couple of errors about Spotify.sublime-package

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 140, in create_window_commands
    cmds.append(class_(window))
  File "sublime_spotify in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 26, in __init__
  File "status_updater in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 32, in __init__
  File "status_updater in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 73, in run
  File "status_updater in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 85, in _run
  File "status_updater in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 55, in _get_message
  File "applescript_spotify_player in /Users/moritz/Library/Application Support/Sublime Text 3/Installed Packages/Spotify.sublime-package", line 58, in get_duration
ValueError: could not convert string to float: 
```

**Comment by smpanaro** [comment]
@iMoritz Okay - I'm having a bit of trouble reproducing this. If you could answer a few questions that might help.
1. Did you install via package control? 
2. Are there any specific conditions that cause this? (Is Spotify already open when you launch Sublime? If so, is it playing?)
3. Are there any other errors related to the plugin or just the one you pasted?

**Comment by moritzsternemann** [comment]
1. Yeah I installed via Package Control
2. I tried with Spotify open and closed although playing and paused
3. Nope this is the only error

**Comment by dawidk92** [comment]
+1

**Comment by dawidk92** [comment]
After install spotify I dont have Package Control anymore
![zrzut ekranu 2015-03-18 o 16 34 01](https://cloud.githubusercontent.com/assets/7023167/6712410/ae0a113c-cd8c-11e4-937c-a836520840d3.png)

**Comment by smpanaro** [comment]
Hmmm. I'm still not sure what could be causing this.
You could try installing the package manually. Just clone the repository to `~/Library/Application Support/Sublime Text 2/Packages/Spotify/` for Sublime 2 or to `~/Library/Application Support/Sublime Text 3/Packages/Spotify/` for Sublime 3.

**Comment by ghost** [comment]
My mac does not have this path ~/Library/Application Support/Sublime Text 3/Packages/Spotify/

Not Path  ~/Library/Application Support/Sublime Text 3

**Comment by smpanaro** [comment]
@guardianserver Are you trying to install manually like I mentioned in my last comment? I would only recommend that if Package Control doesn't work for you.

If that is what you're trying to do, the `~/Library/Application Support/Sublime Text 3/Packages/Spotify/` shouldn't exist. 
To install it manually:
1. Create `~/Library/Application Support/Sublime Text 3/Packages/Spotify/`
2. Clone this project and then copy the contents of the `sublime-spotify` folder into `~/Library/Application Support/Sublime Text 3/Packages/Spotify/`.
